export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_NUMBER = "INCREMENT_NUMBER";
export const DECREMENT_NUMBER = "DECREMENT_NUMBER";
export const INCREMENT2 = "INCREMENT2";
export const DECREMENT2 = "DECREMENT2";